name: dslink_rethinkdb
authors:
  - Logan Gorence <loganjohngorence@gmail.com>
  - Kenneth Endfinger <kaendfinger@gmail.com>
description: RethinkDB for DSA
dependencies:
  dslink:
    git: https://github.com/IOT-DSA/sdk-dslink-dart.git
  rethinkdb_driver: "^2.0.3"
